### ISSUE TITLE
 Permission denied for public-resolvers.md and relays.md

### ISSUE THREAD

**Issue by xorguy** [klutchell/dnscrypt-proxy#15]
Hi.

I have running dnscrypt-proxy with mapped volume to store dnscrypt-proxy.toml configuration file and I'm getting permission denied for both files at docker logs.

[WARNING] /config/public-resolvers.md: open sf-psizzome646u2elx.tmp: permission denied

Both files appeared at mapped volume first time I run, but why is it now showing permission denied? Both files have same user:group like configuration file.

Any way to not have those permission denied?

Thanks.

**Comment by jedisct1** [comment]
Maybe the permissions on the directory are not good?

In such a scenario, I'd just `chmod 777` (yeah, I know) the directory, start the container and see what user the files were created as in order to then set proper permissions on the directory.

**Comment by klutchell** [comment]
Recently the I changed the runtime user from `nonroot` to `nobody:nogroup` so perhaps your existing configuration files still have the old permissions?

If your host OS is Linux, can you share the permissions on your config directory and files?

```
$ ls -al /path/to/config/
```

Also, @jedisct1's suggestion could work so I would try that as well.

**Comment by xorguy** [comment]
@klutchell The files where not created/owned by nobody:nogroup so almost 99% was it, even that I tried to chmod 777, from @jedisct1 comment, the folder and deleting previous files and now the files have correct user and groups and seems that it is working great with no WARNINGs.

**Comment by klutchell** [comment]
Excellent! I'll add a note to the readme that the files in the configuration volume should be either readable by world, or owned by `nobody:nogroup`.

Can we close this issue?

**Comment by xorguy** [comment]
Agree to close!

**Comment by boistordu** [comment]
I would like to say, at least for the future, that on the raspbian version up to date with the dnscrypt-proxy from the official repos from raspbian : 
```
mars 14 20:08:39 redacted sudo[3298]: pam_unix(sudo:session): session closed for user root
mars 14 20:08:39 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:39] [NOTICE] Source [/var/cache/dnscrypt-proxy/public-resolvers.md] loaded
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [WARNING] /etc/dnscrypt-proxy/relays.md: open sf-t6o45zek5ewbhi45.tmp: permission denied
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [WARNING] /etc/dnscrypt-proxy/relays.md.minisig: open sf-mvw7i6ykum2va3jp.tmp: permission dmars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [NOTICE] Source [relays.md] loaded
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [ERROR] Invalid or unsupported stamp: [sdns://gQ01MS4xNTguMTY2Ljk3]
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [CRITICAL] Unable to use source [relays]: [Unsupported stamp version or protocol]
mars 14 20:08:40 redacted dnscrypt-proxy[3301]: [2021-03-14 20:08:40] [NOTICE] dnscrypt-proxy 2.0.19
```

I've followed the advice of @jedisct1 to put 777 and the user is `dnscrypt-proxy` group `nogroup `. Problem process from official repo is in root. So I don't know who is maintaining this repo but that would be nice to put a notice to them ? 

Thanks in advance
