### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by adit-s** [klutchell/dnscrypt-proxy#25]
Hey Kyle. Hope everything is well.
I was trying to get at the dnscrypt logs but can't figure out how to. I can't attach to the container with a shell so can't go in and manually look at the logs. I was wondering if you had any ideas or suggestions?

In the dnscrypt-proxy.toml, there is an option to enable logging:
```
## Log file for the application, as an alternative to sending logs to
## the standard system logging service (syslog/Windows event log).
##
## This file is different from other log files, and will not be
## automatically rotated by the application.

# log_file = 'dnscrypt-proxy.log'
```
Is there a way to view it (or the standard syslog) in the container?

Thanks,
Adit

**Comment by klutchell** [comment]
Hey @adit-s, this image was designed to be "distroless", meaning there is no shell or binaries besides the ones required to run dnscrypt-proxy. This keeps the image very small and reduces the attack surface.

If you want to write logs to a file, I recommend mounting a local volume and enable the log file option in your config to point to a path in that directory.

**Comment by adit-s** [comment]
That worked. Thanks @klutchell.
