### ISSUE TITLE
Problem getting oDoH to work

### ISSUE THREAD

**Issue by rtthane** [klutchell/dnscrypt-proxy#31]
I don't know if this is an issue with the 2.1.0 build or whether there is something I am not doing correctly with the dns-proxy.toml file to get oDoH working. I have set the parameters as I believe they should be. The dnscrypt-proxy shows that the server list has loaded but I am unable to browse any websites. If I switch my config back to use DNSCrypt Anonymised DNS everything works.  Below is an extract from the server log, and an extract of what i have put into the dsncrypt-proxy.toml file,

Thanks.

[2021-08-18 20:04:04] [NOTICE] dnscrypt-proxy is ready - live servers: 7,
[2021-08-18 20:04:04] [NOTICE] Sorted latencies:,
[2021-08-18 20:04:04] [NOTICE] -   212ms odoh-id-gmail,
[2021-08-18 20:04:04] [NOTICE] -    33ms odoh-cloudflare,
[2021-08-18 20:04:04] [NOTICE] -    43ms odoh-koki-ams,
[2021-08-18 20:04:04] [NOTICE] -   108ms odoh-crypto-sx,
[2021-08-18 20:04:04] [NOTICE] -   250ms odoh-jp.tiar.app,
[2021-08-18 20:04:04] [NOTICE] -   276ms odoh-tiarap.org,
[2021-08-18 20:04:04] [NOTICE] -   308ms odoh-jp.tiarap.org,
[2021-08-18 20:04:04] [NOTICE] Server with the lowest initial latency: odoh-cloudflare (rtt: 33ms) 

Changes I have made to the dnscrypt-proxy.toml file

server_names = ['odoh-id-gmail', 'odoh-cloudflare' , 'odoh-crypto-sx' , 'odoh-jp.tiar.app' , 'odoh-jp.tiarap.org' , 'odoh-koki-ams' , 'odoh-tiarap.org']

# Use servers implementing the Oblivious DoH protocol
odoh_servers = true

  ## ODoH (Oblivious DoH) servers and relays

  [sources.'odoh-servers']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/odoh-servers.md', 'https://download.dnscrypt.net/resolvers-list/v3/odoh-servers.md']
    cache_file = 'odoh-servers.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 24
    prefix = ''
  [sources.'odoh-relays']
    urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/odoh-relays.md', 'https://download.dnscrypt.net/resolvers-list/v3/odoh-relays.md']
    cache_file = 'odoh-relays.md'
    minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
    refresh_delay = 24
    prefix = ''

routes = [
    { server_name='odoh-id-gmail', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] },
    { server_name='odoh-cloudflare', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] },
    { server_name='odoh-crypto-sx', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] },
    { server_name='odoh-jp.tiar.app', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] },
    { server_name='odoh-jp.tiarap.org', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] },
    { server_name='odoh-koki-ams', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] },
    { server_name='odoh-tiarap.org', via=['odohrelay-crypto-sx', 'odohrelay-surf' , 'odohrelay-koki-bcn' , 'odohrelay-koki-ams'] }
 ]

**Comment by klutchell** [comment]
Are there any other differences between your config files besides the odoh changes? Are the ports still correct?

Are you able to use your new config file on a workstation with the [dnscrypt-proxy binaries](https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.1.0) without this docker container?

**Comment by rtthane** [comment]
Fixed now - looks like config was corrupt. Thanks for the response.
